cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false
logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
server:
  port: 7070
spring:
  application:
    admin:
      enabled: true
    name: awsservicesstart
  datasource:
    continue-on-error: false
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: ALWAYS
    password: admin
    url: jdbc:mysql://localhost:3306/vikas_personal
    username: root
  devtools:
    add-properties: false
  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  profiles:
    active: dev
  session:
    store-type: none
